### ISSUE TITLE
Is PDFiumLibrary instance reusable?

### ISSUE THREAD

**Issue by swftvsn** [hyzyla/pdfium#1]
Hi, thank you for the excellent work!

Can I reuse PDFiumLibrary instance to read multiple PDFs and manipulate those, or should I initialize a fresh instance per PDF document and then destroy it after manipulating the PDF?

Thanks!

**Comment by hyzyla** [comment]
Sorry for late reply. I create one instance of library per application and then reuse it for different documents

**Comment by swftvsn** [comment]
Thank you for your work! Слава Україні!
