### ISSUE TITLE
Support for Linearized PDFs

### ISSUE THREAD

**Issue by nguyenyou** [hyzyla/pdfium#22]
Could we have example for using `FPDF_LoadCustomDocument` to load pdf file from input stream?

**Comment by hyzyla** [comment]
Hi @nguyenyou this method is not exposed yet. Would you like to contribute?

**Comment by nguyenyou** [comment]
Hi @hyzyla ,
I’d love to help, but I’m not quite sure how the whole thing works. I looked around for examples, and it seems like most people are using the `FPDF_LoadMemDocument` method.
